config/routes.rb
Rails.application.routes.draw do
  root 'home#index', :as => 'containers'

  get 'container/new' => 'containers#new', :as => 'container_new'
  post 'container/new' => 'containers#create', :as => 'container_create'
  get 'container/:id' => 'containers#show', :as => 'container'
  get 'container/:id/start' => 'containers#start', :as => 'container_start'
  get 'container/:id/stop' => 'containers#stop', :as => 'container_stop'
  get 'container/:id/restart' => 'containers#restart', :as => 'container_restart'
  get 'container/:id/commit' => 'containers#commit', :as => 'container_commit'
  get 'container/:id/remove' => 'containers#remove', :as => 'container_remove'

  get 'images' => 'images#index', :as => 'images'
  get 'image/:id' => 'images#show', :as => 'image'
  get 'image/:id/download' => 'images#download', :as => 'image_download'
  delete 'image/:id' => 'images#destroy', :as => 'image_delete'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale

  def set_locale

    if params[:locale]
      session[:locale] = params[:locale]
    end

    locale = session[:locale] || I18n.default_locale
    I18n.locale = locale
  end
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
  def show
    @container = Docker::Container.get(params[:id])
    @logs = @container.logs(stdout: true, stderr: true)
  end

  def new
    _images = Docker::Image.all

    @images = Hash.new
    _images.each_with_index do |image, index|
      @images[image.id.to_s.truncate(12, omission: '')] = image.info['RepoTags'][0]
    end
  end

  def create
    json = Hash.new
    if params[:hostname]
      json['Hostname'] = params[:hostname]
    end

    if params[:image]
      json['Image'] = params[:image]
    else
      json['Image'] = 'debian:latest'
    end

    name = Hash.new
    name['Name'] = 'Peter'
    json['HostConfig'] = Hash.new
    json['HostConfig']['Ulimits'] = name

    @container = Docker::Container.create(json)
    render :json => json
    # flash[:success] = 'Der Container wurde erfolgreich erstellt.'
    # redirect_to container_path @container.id
  end

  def start
    @container = Docker::Container.get(params[:id])
    @container.start

    @container = Docker::Container.get(params[:id])
    state = @container.info['State']['Status']

    if state == 'running'
      flash[:success] = 'Der Container wurde erfolgreich gestartet.'
      redirect_to container_path
    else
      flash[:error] = 'Der Container konnte nicht gestartet werden.'
      redirect_to container_path
    end
  end

  def stop
    @container = Docker::Container.get(params[:id])
    @container.stop

    @container = Docker::Container.get(params[:id])
    state = @container.info['State']['Status']

    if state == 'exited'
      flash[:success] = 'Der Container wurde erfolgreich gestopt.'
      redirect_to container_path
    else
      flash[:error] = 'Der Container konnte nicht gestopt werden.'
      redirect_to container_path
    end
  end

  def restart
    @container = Docker::Container.get(params[:id])
    @container.restart

    @container = Docker::Container.get(params[:id])
    state = @container.info['State']['Status']

    if state == 'running'
      flash[:success] = 'Der Container wurde erfolgreich neugestartet.'
      redirect_to container_path
    else
      flash[:error] = 'Der Container konnte nicht neugestartet werden.'
      redirect_to container_path
    end
  end

  def commit
    @container = Docker::Container.get(params[:id])
    @container.commit
    flash[:success] = 'Der Container wurde erfolgreich "committet".'
    redirect_to container_path
  end

  def remove
    @container = Docker::Container.get(params[:id])
    state = @container.info['State']['Status']
    # render :json => state
    if state == 'running'
      flash[:error] = 'Der Container muss zuerst gestopt werden.'
      redirect_to container_path
    elsif state == 'exited'
      @container.remove
      flash[:error] = 'Der Container wurde gelöscht.'
      redirect_to containers_path
    else
      flash[:error] = 'Unbekannter Fehler.'
      redirect_to container_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @containers = Docker::Container.all(:all => true)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Docker::Image.all
    # @search = Docker::Image.search(:term => 'htop')
  end

  def show
    @image = Docker::Image.get(params[:id])
  end

  def destroy
    if Docker::Image.exist?(params[:id])
      image = Docker::Image.get(params[:id])
      image.remove

      if !Docker::Image.exist?(params[:id])
        flash[:success] = 'Das Image wurde erfolgreich gelöscht.'
      else
        flash[:error] = 'Fehler beim löschen des Images.'
      end
    end
    redirect_to images_path
  end

  def create
    Docker::Image.create('fromImage' => params[:name])
  end

  def download
    image = Docker::Image.get(params[:id])
    file = 'public/images/'+image.id+'.tar'
    if !File.exist?(file)
      image.save(file)
    end

    download_file(file)
  end

  private

  def download_file file
    type = MIME::Types.type_for(file).first.content_type
    send_file file, :type=> type, :x_sendfile => true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def glyph(*names)
    content_tag :i, nil, class: names.map{|name| "glyphicon glyphicon-#{name.to_s.gsub('_','-')}" }
  end

  def bootstrap_class_for flash_type
    case flash_type
      when 'success'
        "alert-success" # Green
      when 'error'
        "alert-danger" # Red
      when 'alert'
        "alert-warning" # Yellow
      when 'notice'
        "alert-info" # Blue
      else
        flash_type.to_s
    end
  end

end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/containers/new.html.haml
.row
  .col-sm-12
    .panel.panel-default
      .panel-heading
        %h3.panel-title
          = t 'container.new.title'
      .panel-body
        .col-sm-9
          = form_tag container_create_path, :method => :post do
            .form-group
              = label_tag :hostname, t('container.new.hostname')
              = text_field_tag :hostname, "", :class => "form-control", :placeholder => "dockerui.on.rails"

            .form-group
              = label_tag :user, t('container.new.user')
              = text_field_tag :user, "", :class => "form-control"

            .form-group
              = label_tag :attachstdin, t('container.new.attach_stdin')
              = check_box_tag :attachstdin, "", false, :data => {:name => "switch"}

            .form-group
              = label_tag :attachstdout, t('container.new.attach_stdout')
              = check_box_tag :attachstdout, "", false, :data => {:name => "switch"}

            .form-group
              = label_tag :attachstderr, t('container.new.attach_stderr')
              = check_box_tag :attachstderr, "", false, :data => {:name => "switch"}

            .form-group
              = label_tag :env, t('container.new.env')
              = text_area_tag :env, "", :class => "form-control", :placeholder => "var1=val1, var2=val2, var3=val3"

            .form-group
              = label_tag :cmd, t('container.new.cmd')
              = text_field_tag :cmd, "", :class => "form-control", :placeholder => "./run.sh"

            .form-group
              = label_tag :entrypoint, t('container.new.entrypoint')
              = text_field_tag :entrypoint, "", :class => "form-control", :placeholder => ""

            .form-group
              = label_tag :image, t('container.new.image')
              %select{:name => "image", :data => {:name => "select2"}}
                - @images.each do |image|
                  %option{:value => image[1]}
                    = image[1]

            .form-group
              = label_tag :workingdir, t('container.new.working_dir')
              = text_field_tag :workingdir, "", :class => "form-control", :placeholder => ""
            .form-group
            .form-group
            .form-group
            .form-group
            .form-group
            .form-group
            .form-group
            .form-group
              = submit_tag t('container.new.btn.submit'), :class => "btn btn-primary"
              = link_to t('container.new.btn.cancle'), containers_path, :class => "btn btn-danger"

app/views/containers/show.html.haml
%nav
  %ul.pager
    %li.previous
      = link_to containers_path do
        %span{"aria-hidden" => "true"} &larr;
        = t 'application.nav.back_to'

%h1
  %span{ data: { toggle: "tooltip", placement: "right" }, :title => @container.id.truncate(12, omission: '') }
    = @container.info['Name']

%ul.nav.nav-tabs{:role => "tablist"}
  %li.active{:role => "presentation"}
    %a{"aria-controls" => "home", "data-toggle" => "tab", :href => "#home", :role => "tab"}
      = t 'container.show.nav.tabs.information'

  %li{:role => "presentation"}
    %a{"aria-controls" => "profile", "data-toggle" => "tab", :href => "#logs", :role => "tab"}
      = t 'container.show.nav.tabs.logs'

.tab-content
  #home.tab-pane.active{:role => "tabpanel"}
    .col-sm-8
      %br
      .panel.panel-default
        .panel-heading
          %h3.panel-title
            = t 'container.show.boxes.action.title'
        .panel-body
          .control-btn.clearfix
            - if @container.info['State']['Status'] == 'exited' || @container.info['State']['Status'] == 'created'
              = button_to t('container.show.boxes.action.start'), { :controller => :containers, :action => :start }, { :method => :get, :class => "btn btn-primary" }
            - else
              = button_to t('container.show.boxes.action.start'), { :controller => :containers, :action => :start }, { :method => :get, :class => "btn btn-primary", :disabled => true }

            - if @container.info['State']['Status'] == 'running'
              = button_to t('container.show.boxes.action.stop'), { :controller => :containers, :action => :stop }, { :method => :get, :class => "btn btn-warning" }
              = button_to t('container.show.boxes.action.restart'), { :controller => :containers, :action => :restart }, { :method => :get, :class => "btn btn-info" }
              = button_to t('container.show.boxes.action.remove'), { :controller => :containers, :action => :remove }, { :method => :get, :class => "btn btn-danger", :disabled => true }
            - elsif @container.info['State']['Status'] == 'created'
              = button_to t('container.show.boxes.action.stop'), { :controller => :containers, :action => :stop }, { :method => :get, :class => "btn btn-warning", :disabled => true }
              = button_to t('container.show.boxes.action.restart'), { :controller => :containers, :action => :restart }, { :method => :get, :class => "btn btn-info" }
              = button_to t('container.show.boxes.action.remove'), { :controller => :containers, :action => :remove }, { :method => :get, :class => "btn btn-danger", :disabled => true }
            - else
              = button_to t('container.show.boxes.action.stop'), { :controller => :containers, :action => :stop }, { :method => :get, :class => "btn btn-warning", :disabled => true }
              = button_to t('container.show.boxes.action.restart'), { :controller => :containers, :action => :restart }, { :method => :get, :class => "btn btn-info", :disabled => true }
              = button_to t('container.show.boxes.action.remove'), { :controller => :containers, :action => :remove }, { :method => :get, :class => "btn btn-danger" }

      .panel.panel-default
        .panel-heading
          %h3.panel-title
            = t 'container.show.boxes.basic_information.title'
        .panel-body.no-padding
          %table.table.table-striped.mb-0
            %tbody
              %tr
                %td
                  = t 'container.show.boxes.basic_information.title'
                %td
                  = @container.info['Name']
              %tr
                %td
                  = t 'container.show.boxes.basic_information.status'
                %td.w-100
                  - status = @container.info['State']['Status']
                  - if status == 'running'
                    %span.label.label-success
                      = status
                  - else
                    %span.label.label-warning
                      = status
              %tr
                %td
                  = t 'container.show.boxes.basic_information.privileged'
                %td
                  = @container.info['HostConfig']['Privileged']
              %tr
                %td
                  = t 'container.show.boxes.basic_information.pid'
                %td.w-100
                  = @container.info['State']['Pid']
              %tr
                %td
                  = t 'container.show.boxes.basic_information.image'
                %td.w-100
                  = link_to image_path @container.info['Image'].truncate(12, omission: '') do
                    = @container.info['Image'].truncate(12, omission: '')
              %tr
                %td
                  = t 'container.show.boxes.basic_information.restart_count'
                %td
                  = @container.info['RestartCount']
              %tr
                %td
                  = t 'container.show.boxes.basic_information.driver'
                %td
                  = @container.info['Driver']

      .panel.panel-default
        .panel-heading
          %h3.panel-title
            = t 'container.show.boxes.env.title'
        .panel-body.no-padding
          %table.table.table-striped.mb-0
            %tbody
              - if @container.info['Config']['Env']
                %tr
                  %td
                    = t 'container.show.boxes.env.env'
                  %td.w-100
                    = @container.info['Config']['Env'].join("<br>").html_safe

    .col-sm-4
      %br
      .panel.panel-default
        .panel-heading
          %h3.panel-title
            = t 'container.show.boxes.network.title'
        .panel-body.no-padding
          - network = @container.info['NetworkSettings']
          %table.table.table-striped.mb-0
            %tbody
            %tr
              %td
                = t 'container.show.boxes.network.ports'
              %td
                - if network['Ports'].to_a.kind_of?(Array)
                  - network['Ports'].to_a.each do |port|
                    - if port[1]
                      #{port[1][0]['HostIp']}:#{port[1][0]['HostPort']}
                      \->
                    = port[0]
                    %br/
            %tr
              %td
                = t 'container.show.boxes.network.gateway'
              %td
                = network['Gateway']
            %tr
              %td
                = t 'container.show.boxes.network.ip_adress'
              %td
                = network['IPAddress']
            %tr
              %td
                = t 'container.show.boxes.network.mac_adress'
              %td
                = network['MacAddress']

      - volumes = @container.info['HostConfig']['Binds'].to_a
      - if volumes.kind_of?(Array) && volumes.count > 0
        .panel.panel-default
          .panel-heading
            %h3.panel-title
              = t 'container.show.boxes.volumes.title'
          .panel-body.no-padding
            %table.table.table-striped.mb-0
              %tbody
                - volumes.to_a.each do |vol|
                  %tr
                    %td
                      = vol.gsub(":", " : ")

      .panel.panel-default
        .panel-heading
          %h3.panel-title
            = t 'container.show.boxes.configuration.title'
        .panel-body.no-padding
          - config = @container.info['Config']
          %table.table.table-striped.mb-0
            %tbody
            %tr
              %td
                = t 'container.show.boxes.configuration.Hostname'
              %td
                = config['Hostname']
            %tr
              %td
                = t 'container.show.boxes.configuration.attach_stdin'
              %td
                = config['AttachStdin']
            %tr
              %td
                = t 'container.show.boxes.configuration.attach_stdout'
              %td
                = config['AttachStdout']
            %tr
              %td
                = t 'container.show.boxes.configuration.attach_stderr'
              %td
                = config['AttachStderr']
            %tr
              %td
                = t 'container.show.boxes.configuration.tty'
              %td
                = config['Tty']
            %tr
              %td
                = t 'container.show.boxes.configuration.image'
              %td
                = link_to image_path @container.info['Image'].truncate(12, omission: '') do
                  = config['Image']
            %tr
              %td
                = t 'container.show.boxes.configuration.entrypoint'
              %td
                - if config['Entrypoint'].kind_of?(Array)
                  = config['Entrypoint'].join(", ")
                - else
                  = config['Entrypoint']
            %tr
              %td
                = t 'container.show.boxes.configuration.memory'
              %td
                = config['Memory']
            %tr
              %td
                = t 'container.show.boxes.configuration.memory_swap'
              %td
                = config['MemorySwap']
            %tr
              %td
                = t 'container.show.boxes.configuration.cpu_shares'
              %td
                = config['CpuShares']

            - if config['Cpuset'].length > 0
              %tr
                %td
                  = t 'container.show.boxes.configuration.cpuset'
                %td
                  = config['Cpuset']

  #logs.tab-pane{:role => "tabpanel"}
    %br
    %pre
      = @logs

app/views/home/index.html.haml
.row
  .col-sm-12
    %span.pull-right
      = link_to container_new_path, :class => 'btn btn-default btn-sm', :id => 'open-container-wizard' do
        = t 'container.index.create'

  %div.clearfix
    %br
    %br

  .col-sm-12
    .panel.panel-default.clearfix
      .panel-heading
        %h3.panel-title
          = t 'container.index.title'

      .panel-body
        .table-responsive
          %table.table-condensed.table-striped.table-hover.w-100.mb-0
            %thead
              %tr
                %th
                  = t 'container.index.table.name'
                %th
                  = t 'container.index.table.id'
                %th
                  = t 'container.index.table.image'
                %th
                  = t 'container.index.table.command'
                %th
                  = t 'container.index.table.created'
                %th
                  = t 'container.index.table.status'
                %th
                  = t 'container.index.table.ports'

            %tbody
              - @containers.each do |container|
                %tr
                  %td
                    = link_to container_path container.id.to_s.truncate(12, omission: '') do
                      = container.info['Names'].join(', ')
                  %td
                    = link_to container_path container.id.to_s.truncate(12, omission: '') do
                      = container.id.to_s.truncate(12, omission: '')
                  %td
                    = link_to image_path container.info['ImageID'].truncate(12, omission: '') do
                      = container.info['Image']
                  %td
                    = container.info['Command']
                  %td
                    = Time.at(container.info['Created']).strftime('%d.%m.%Y %H:%M')
                  %td
                    - str = container.info['Status']
                    - if str.include? 'Up'
                      %span.label.label-success
                        = str
                    - elsif str.include? 'Exited'
                      %span.label.label-warning
                        = str
                    - else
                      1
                  %td
                    - container.info['Ports'].each do |port|
                      - if port['PublicPort']
                        = port['PublicPort']
                        \->
                      = port['PrivatePort']
                      \/
                      = port['Type']
                      %br

app/views/images/index.html.haml
.row
  .col-sm-12

.row
  .col-sm-12
    .panel.panel-default
      .panel-heading
        %h3.panel-title Images
      .panel-body
        %p
          Hier werden die heruntergeladenen Images angezeigt von denen man einen Container erstellen kann.
        / %hr
        .table-responsive
          %table.table-condensed.table-striped.table-hover.w-100
            %thead
              %tr
                %th
                  ID
                %th
                  RepoTag
                %th
                  Created
                %th
                  VirtualSize
                %th
                  Action

            %tbody
              - @images.each do |image|
                %tr
                  %td
                    = link_to image_path image.id.to_s.truncate(12, omission: '') do
                      = image.id.to_s.truncate(12, omission: '')
                  %td
                    = link_to image_path image.id.to_s.truncate(12, omission: '') do
                      = image.info['RepoTags'][0]
                  %td
                    = Time.at(image.info['Created']).strftime('%d.%m.%Y %H:%M')
                    Uhr
                  %td
                    = number_to_human_size(image.info['VirtualSize'], precision: 3)
                  %td
                    = link_to image_delete_path(image.id.to_s.truncate(12, omission: '')), :method => :delete, data: { confirm: "Das Image löschen?", toggle: "tooltip", placement: "top" }, :title => "delete image" do
                      = glyph(:remove)

                    / = link_to image_download_path(image.id.to_s.truncate(12, omission: '')), data: { toggle: "tooltip", placement: "top" }, :title => "download image" do
                    /   = glyph(:download_alt)

app/views/images/show.html.haml
%h1
  = @image.info['RepoTags'][0]
%p Find me in app/views/images/show.html.haml

NOT READY!!!

/ = @image.inspect

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title
      = t 'application.title'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to t('application.title'), '/', :class => 'navbar-brand'
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              = link_to t('application.nav.images'), images_path
          %ul.nav.navbar-nav.navbar-right
            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                = t 'application.nav.languages'
                %span.caret
              %ul.dropdown-menu
                %li
                  %a{:href => "?locale=en"}
                    %span.flag-icon.flag-icon-gb
                    %span
                      = t 'languages.en'
                %li
                  %a{:href => "?locale=de"}
                    %span.flag-icon.flag-icon-de
                    %span
                      = t 'languages.de'

    .container
      = render partial: "shared/flash_messages", flash: flash
      = yield

app/views/shared/_flash_messages.html.haml
- flash.each do |type, message|
  %div{:class => "alert #{bootstrap_class_for(type)}", :role => "alert"}
    %button.close{"data-dismiss" => "alert"} ×
    = message